### ISSUE TITLE
Deploy our Vue.js app on Azure.

### ISSUE THREAD

**Issue by mohamedMahameed** [TechnionYearlyProject/DailyPulseMe#108]

**Comment by mohamedMahameed** [comment]
I searched the topic and found these tutorials : 
- creating a Node.js in Azure : 
https://docs.microsoft.com/en-us/azure/app-service/app-service-web-get-started-nodejs 

- deploying Node.js app to Azure from git: 
https://docs.microsoft.com/en-us/azure/app-service/app-service-deploy-local-git 

I am going to need someone who understands the files and the parts of the front end app for making this ready faster and easier.

**Comment by najeeb95** [comment]
Time estimated: 9 hours.

**Comment by najeeb95** [comment]
Time it took: 12 hours from each member assigned.
