### ISSUE TITLE
issue for photos upload

### ISSUE THREAD

**Issue by mabdalazez** [TechnionYearlyProject/DailyPulseMe#121]

**Comment by mabdalazez** [comment]
this issue i have opened just so i can take the photos links from here and paste in the wiki so dont give him attention

**Comment by mabdalazez** [comment]
![manualaccount](https://user-images.githubusercontent.com/33095175/41595823-d6d32476-73d0-11e8-828d-c3d3c6075192.PNG)

**Comment by mabdalazez** [comment]
![signuppage](https://user-images.githubusercontent.com/33095175/41596091-d3751004-73d1-11e8-91e1-43f9627471e8.PNG)
![log-in](https://user-images.githubusercontent.com/33095175/41596103-dce0ab8a-73d1-11e8-87bc-384ab8753336.PNG)

**Comment by mabdalazez** [comment]
![googleaccount](https://user-images.githubusercontent.com/33095175/41596423-ff055368-73d2-11e8-87ee-721bdb7c1d3b.PNG)
![googlesignup](https://user-images.githubusercontent.com/33095175/41596468-24a93756-73d3-11e8-8387-a6b667a2fe1a.PNG)

**Comment by mabdalazez** [comment]
![googlewizard](https://user-images.githubusercontent.com/33095175/41609347-3f47d55c-73f3-11e8-961f-a844f4c6e27a.PNG)
![microsoftwizard](https://user-images.githubusercontent.com/33095175/41609357-44c4b63a-73f3-11e8-9ce4-e8cebe8b58e7.PNG)
![fitbitaccount](https://user-images.githubusercontent.com/33095175/41609378-50ec1232-73f3-11e8-96fe-4ee9ee781891.PNG
![calendarclick](https://user-images.githubusercontent.com/33095175/41609540-ae589a3a-73f3-11e8-97b1-2e3089f73734.PNG
![events](https://user-images.githubusercontent.com/33095175/41609632-f51ed0b0-73f3-11e8-86ed-7f689c7de18b.PNG)
)
)

**Comment by mabdalazez** [comment]
![graphsclick](https://user-images.githubusercontent.com/33095175/41609707-1f6d3dc0-73f4-11e8-934f-84a45d966c62.PNG)
![graphslook](https://user-images.githubusercontent.com/33095175/41609710-21864dfe-73f4-11e8-9634-ad3869d9b2cc.PNG
![graphslook](https://user-images.githubusercontent.com/33095175/41610030-c91cd1f0-73f4-11e8-9855-35f387aecd84.PNG)
)
![double](https://user-images.githubusercontent.com/33095175/41609865-6c4e052a-73f4-11e8-9020-ace27151d8e9.PNG)

**Comment by mabdalazez** [comment]
![subscribebutton](https://user-images.githubusercontent.com/33095175/41610363-ae860a72-73f5-11e8-826e-e8c1b86dc31e.PNG)
![unsubscribe](https://user-images.githubusercontent.com/33095175/41610372-b1d87174-73f5-11e8-957e-e23ed9f78f02.PNG)

**Comment by mabdalazez** [comment]
![sign](https://user-images.githubusercontent.com/33095175/41782377-bdd7a69e-7642-11e8-9316-86f528efb49f.PNG)
![login](https://user-images.githubusercontent.com/33095175/41782381-c02415e0-7642-11e8-9ed5-c408e3ddc06a.PNG)
![token](https://user-images.githubusercontent.com/33095175/41782554-4306a68a-7643-11e8-8049-8d43066aea3c.PNG
![headers](https://user-images.githubusercontent.com/33095175/41782683-98252920-7643-11e8-8dd5-d454373e6158.PNG)
)
![addev](https://user-images.githubusercontent.com/33095175/41782694-a2550884-7643-11e8-965b-0751594ecdad.PNG)

**Comment by mohamedMahameed** [comment]
![image](https://user-images.githubusercontent.com/33042263/41787380-e88d8db4-7650-11e8-9d61-ad8e6480b2a9.png)

**Comment by mohamedMahameed** [comment]
![image](https://user-images.githubusercontent.com/33042263/41787442-23433710-7651-11e8-93a9-81756cca7e54.png)

**Comment by mohamedMahameed** [comment]
![image](https://user-images.githubusercontent.com/33042263/41787903-83ce9c4a-7652-11e8-945e-cacf161ba9ce.png)

**Comment by mohamedMahameed** [comment]
![image](https://user-images.githubusercontent.com/33042263/41788371-1b2690b0-7654-11e8-8ab3-251757bf0f8e.png)

**Comment by mohamedMahameed** [comment]
![image](https://user-images.githubusercontent.com/33042263/41788442-41b4f9ce-7654-11e8-8bc5-a8ac2e932488.png)

**Comment by mohamedMahameed** [comment]
![image](https://user-images.githubusercontent.com/33042263/41788734-51a3cefe-7655-11e8-8551-64dfdaaf5fb2.png)

**Comment by mohamedMahameed** [comment]
![image](https://user-images.githubusercontent.com/33042263/41791137-865af07a-765d-11e8-8e1e-77e20c4fee0d.png)

**Comment by mohamedMahameed** [comment]
![image](https://user-images.githubusercontent.com/33042263/41791207-c1fbbdd0-765d-11e8-8e77-40c057a4649a.png)

**Comment by mohamedMahameed** [comment]
![image](https://user-images.githubusercontent.com/33042263/41791281-fd0f84ce-765d-11e8-8860-249ce569f1ae.png)

**Comment by anadilhussein** [comment]
![dailypulseme2](https://user-images.githubusercontent.com/33092359/41808991-bed69666-76ee-11e8-8cda-cda45fec715d.png)

**Comment by najeeb95** [comment]
![img-1](https://user-images.githubusercontent.com/29060164/41817987-6d27ba32-77ae-11e8-941a-d8cdb249c5ed.png)
![img0](https://user-images.githubusercontent.com/29060164/41817990-74d00ef6-77ae-11e8-84b4-fd38a3f4bd24.png)
![img3](https://user-images.githubusercontent.com/29060164/41817993-7d86a4e2-77ae-11e8-8dc4-26ffd96355c9.png)
![img4](https://user-images.githubusercontent.com/29060164/41817994-7dc67126-77ae-11e8-9f74-5321da517334.png)
![img1](https://user-images.githubusercontent.com/29060164/41817995-7e044014-77ae-11e8-9f4d-32383549b4b6.png)
![img2](https://user-images.githubusercontent.com/29060164/41817997-7e42e134-77ae-11e8-9cba-ddc4100ba4d2.png)

**Comment by anadilhussein** [comment]
![aaaaaaaaaaaaaa](https://user-images.githubusercontent.com/33092359/41871971-2dae0d04-78c9-11e8-86eb-19923b7430b1.png)
