### ISSUE TITLE
Gadgets - should we find an alternative?

### ISSUE THREAD

**Issue by rob94sh** [TechnionYearlyProject/DailyPulseMe#72]
As discussed in the previous semester and in issue #37 we wanted to use Gadgets to add data to the google calendar events. But as explained in issue #4 a message explaining that this feature is going to be deprecated.
Now, trying to reach any link or site that holds information about the use of Gadgets by google returns a 404 error message, meaning that support for Gadgets stopped but the feature may still remain.
The goal of this issue is to research whether it is still possible to use gadgets now and in the future.
If yes, then we shall continue our plans as usual, if no then we need to find an alternative for viewing the relevant data in the google calendar, or alternatively find a way to display the data in some other way if the latter option is unavailable aswell.

**Comment by pelegyair** [comment]
i started research about this on #74 (:
